# Generated by Django 3.2.2 on 2021-06-10 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_alter_product_p_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_QUANTITY', models.IntegerField(default=1, null=None)),
                ('B_STATUS', models.IntegerField(choices=[(0, 'ORDERED'), (1, 'SHIPPED'), (2, 'DELIVERED')], default=0)),
                ('B_DATE', models.DateTimeField(auto_now=True)),
                ('B_PRODUCT', models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('B_USER', models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
