# Generated by Django 3.2.2 on 2021-06-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='B_PRICE',
            field=models.FloatField(default=50, null=None),
            preserve_default=False,
        ),
    ]
