# Generated by Django 3.2.2 on 2021-06-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_batch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
