# Generated by Django 3.2.2 on 2021-05-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='P_STATUS',
            field=models.IntegerField(choices=[(0, 'INACTIVE'), (1, 'ACTIVE')], default=1),
        ),
    ]
