# Generated by Django 3.2.2 on 2021-05-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_p_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='P_SLUG',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
