# Generated by Django 3.2.2 on 2021-05-22 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_alter_product_p_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_QTY', models.IntegerField(default=1, null=None)),
                ('C_DATE', models.DateTimeField(auto_now=True)),
                ('P_ID', models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('U_ID', models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
