# Generated by Django 3.2.2 on 2021-05-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210529_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='QTY',
            new_name='QUANTITY',
        ),
    ]
