# Generated by Django 3.2.2 on 2021-05-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_qty_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='DATE',
            new_name='C_DATE',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='PRODUCT',
            new_name='C_PRODUCT',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='QUANTITY',
            new_name='C_QUANTITY',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='USER',
            new_name='C_USER',
        ),
    ]
