# Generated by Django 3.2.2 on 2021-05-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='P_STATUS',
            new_name='P_STATUSs',
        ),
    ]
