# Generated by Django 3.2.2 on 2021-05-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_p_status_products_p_statuss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='P_PRICE',
            new_name='P_PRICES',
        ),
        migrations.RemoveField(
            model_name='products',
            name='P_STATUSs',
        ),
        migrations.RemoveField(
            model_name='products',
            name='P_STOCK',
        ),
    ]
