# Generated by Django 3.2.2 on 2021-05-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210518_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='P_PRICES',
            new_name='P_PRICE',
        ),
        migrations.AddField(
            model_name='products',
            name='P_STATUS',
            field=models.IntegerField(choices=[(0, 'INACTIVE'), (1, 'ACTIVE')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='P_STOCK',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
