# Generated by Django 3.2.2 on 2021-05-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210518_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='P_STOCK',
            new_name='P_STOCKs',
        ),
    ]
