# Generated by Django 3.2.2 on 2021-05-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_p_stock_products_p_stocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='P_STOCKs',
            new_name='P_STOCK',
        ),
    ]
