# Generated by Django 3.2.2 on 2021-05-18 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_p_stocks_products_p_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='P_DATE',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
